language: python
python: 2.7
env:
- TOXENV=py26
- TOXENV=py27
install:
- pip install tox --use-mirrors
- pip install -r requirements.txt --use-mirrors
- pip install -r test-requirements.txt --use-mirrors
script:
- tox
after_script:
- rm -rf /var/log/company
branches:
  only:
    - master
